---
- name: Add Docker API Repository key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker Ubuntu Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes
    filename: docker

- name: Install Docker
  apt:
    name: docker-ce

- name: Install docker-compose for Python 3
  pip:
    name: docker-compose
