- name: Ubuntu Upgrade
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Install Ubuntu Packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - python3-pip
      - unattended-upgrades
      - vim
      - mc
      - tmux
      - curl
      - bash-completion
    state: present
  tags:
    - packages

- name: Check if bash-completion in enable for root user
  command: grep -q "/etc/bash_completion" /root/.bashrc
  register: check_bashcompletion_enabled
  ignore_errors: True
  changed_when: false

- name: Enable bach-completion for root user
  command: cp /etc/skel/.bashrc /root/.bashrc
  when: check_bashcompletion_enabled.rc == 1

- name: Upgrade pip
  pip:
    name: pip==18.1
    state: present
